"""
Seed mobs table from mobs_seed.csv (generated by export_mobs_csv.py).
Run: python seed_mobs_csv.py
"""
import csv
import os
from db_manager import init_db, upsert_mob

CSV_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "mobs_seed.csv")


def _int(val):
    try:
        return int(val)
    except (TypeError, ValueError):
        return 0


def run():
    init_db()
    added = skipped = 0
    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            mob = {
                "name":         row["name"],
                "description":  row["description"],
                "ac":           _int(row["ac"]),
                "hp_formula":   row["hp_formula"],
                "hp_avg":       _int(row["hp_avg"]),
                "speed":        row["speed"],
                "str":          _int(row["str"]),
                "dex":          _int(row["dex"]),
                "con":          _int(row["con"]),
                "int":          _int(row["int"]),
                "wis":          _int(row["wis"]),
                "cha":          _int(row["cha"]),
                "challenge":    row["challenge"],
                "xp":           _int(row["xp"]),
                "size":         row["size"],
                "mob_type":     row["mob_type"],
                "alignment":    row["alignment"],
                "melee_mod":    row["melee_mod"],
                "ranged_mod":   row["ranged_mod"],
                "attack1":      row["attack1"],
                "attack1_range": row["attack1_range"],
                "attack1_dmg":  row["attack1_dmg"],
                "attack2":      row["attack2"],
                "attack2_range": row["attack2_range"],
                "attack2_dmg":  row["attack2_dmg"],
                "attack3":      row["attack3"],
                "attack3_range": row["attack3_range"],
                "attack3_dmg":  row["attack3_dmg"],
                "source":       row["source"],
                "notes":        row["notes"],
                "languages":    row["languages"],
            }
            try:
                upsert_mob(mob)
                added += 1
            except Exception as e:
                print(f"  Skipped {row['name']}: {e}")
                skipped += 1

    print(f"Done — {added} mobs added/updated, {skipped} skipped.")


if __name__ == "__main__":
    run()
