"""
seed_spells.py
Upserts complete D&D 5e PHB/SRD spell data into spells_reference.
Adds cantrips (level 0), fills all empty fields, fixes typos, cleans classes/source.
Safe to re-run.
"""

import sys
from db_manager import init_db, upsert_spell_reference, count_spells_reference

# ── helpers ────────────────────────────────────────────────────────────────────
B  = "Bard"
C  = "Cleric"
D  = "Druid"
P  = "Paladin"
Ra = "Ranger"
S  = "Sorcerer"
Wa = "Warlock"
Wi = "Wizard"
Ro = "Rogue"   # Arcane Trickster

def sp(name, level, school, ct, rng, comp, dur, conc=False, ritual=False,
       save="", classes=None, source="PHB", desc=""):
    return {
        "name": name, "level": level, "school": school,
        "casting_time": ct, "range": rng, "components": comp,
        "duration": dur, "concentration": conc, "ritual": ritual,
        "save_type": save, "classes": classes or [], "source": source,
        "description": desc,
    }

# ── CANTRIPS (level 0) ─────────────────────────────────────────────────────────
CANTRIPS = [
    sp("Acid Splash",      0,"Conjuration","1 action","60 ft","V,S","Instantaneous",
       save="DEX", classes=[S,Wi],
       desc="Hurl a bubble of acid. One or two creatures within 5 ft of each other must succeed on a DEX save or take 1d6 acid damage."),
    sp("Blade Ward",       0,"Abjuration","1 action","Self","V,S","1 round",
       classes=[B,S,Wa,Wi],
       desc="Extend your hand and trace a sigil of warding. Until the end of your next turn, you have resistance to bludgeoning, piercing, and slashing damage from weapon attacks."),
    sp("Chill Touch",      0,"Necromancy","1 action","120 ft","V,S","1 round",
       classes=[S,Wa,Wi],
       desc="Make a ranged spell attack. On a hit, deal 1d8 necrotic damage and the target can't regain HP until the start of your next turn. Undead also have disadvantage on attacks against you."),
    sp("Dancing Lights",   0,"Evocation","1 action","120 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, classes=[B,S,Wi],
       desc="Create up to four torch-sized lights within range. As a bonus action, move the lights up to 60 ft to new spots within range."),
    sp("Druidcraft",       0,"Transmutation","1 action","30 ft","V,S","Instantaneous",
       classes=[D],
       desc="Predict weather, make a flower bloom, create a sensory effect, or light/snuff a candle/torch."),
    sp("Eldritch Blast",   0,"Evocation","1 action","120 ft","V,S","Instantaneous",
       classes=[Wa],
       desc="A beam of crackling energy. Make a ranged spell attack; on a hit deal 1d10 force damage. Extra beams at higher levels: 2 beams at 5th, 3 at 11th, 4 at 17th."),
    sp("Fire Bolt",        0,"Evocation","1 action","120 ft","V,S","Instantaneous",
       classes=[S,Wi],
       desc="Hurl a mote of fire. Make a ranged spell attack; on a hit deal 1d10 fire damage. Flammable objects ignite."),
    sp("Friends",          0,"Enchantment","1 action","Self","S,M","Concentration, up to 1 minute",
       conc=True, classes=[B,S,Wa,Wi],
       desc="You have advantage on CHA checks directed at one creature for the duration. When the spell ends, the target knows it was charmed."),
    sp("Guidance",         0,"Divination","1 action","Touch","V,S","Concentration, up to 1 minute",
       conc=True, classes=[C,D],
       desc="Touch a willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check."),
    sp("Light",            0,"Evocation","1 action","Touch","V,M","1 hour",
       classes=[B,C,S,Wi],
       desc="Touch one object up to 10 ft across. It sheds bright light in a 20-ft radius and dim light for an additional 20 ft. Creatures in darkness can be blinded (DEX save) by this light."),
    sp("Mage Hand",        0,"Conjuration","1 action","30 ft","V,S","1 minute",
       classes=[B,S,Wa,Wi],
       desc="A spectral, floating hand appears. It can manipulate objects, open doors/containers, stow/retrieve items, or pour out liquids within 30 ft. Cannot attack or carry more than 10 lbs."),
    sp("Mending",          0,"Transmutation","1 minute","Touch","V,S,M","Instantaneous",
       classes=[B,C,D,S,Wi],
       desc="Repair a single break or tear in an object. The break must be no larger than 1 foot in any dimension."),
    sp("Message",          0,"Transmutation","1 action","120 ft","V,S,M","1 round",
       classes=[B,S,Wi],
       desc="Whisper a message to a creature within range. It can reply in a whisper only you can hear. Does not need line of sight; can travel around corners."),
    sp("Minor Illusion",   0,"Illusion","1 action","30 ft","S,M","1 minute",
       classes=[B,S,Wa,Wi],
       desc="Create a sound (up to a creature's shout) or image (up to 5-ft cube). Creatures can investigate with INT (Investigation) check vs your spell save DC."),
    sp("Poison Spray",     0,"Conjuration","1 action","10 ft","V,S","Instantaneous",
       save="CON", classes=[D,S,Wa,Wi],
       desc="Extend your hand toward a creature within range and project a puff of noxious gas. CON save or take 1d12 poison damage."),
    sp("Prestidigitation", 0,"Transmutation","1 action","10 ft","V,S","Up to 1 hour",
       classes=[B,S,Wa,Wi],
       desc="Minor magical tricks: create an effect, light or snuff a flame, clean/soil an object, chill/warm/flavor up to 1 cubic foot, make a color/mark/symbol appear, create a non-magical trinket."),
    sp("Produce Flame",    0,"Conjuration","1 action","Self","V,S","10 minutes",
       classes=[D],
       desc="A flame appears in your hand, shedding bright light 10 ft and dim light 20 ft. You can hurl it as a ranged spell attack (30 ft) for 1d8 fire damage."),
    sp("Ray of Frost",     0,"Evocation","1 action","60 ft","V,S","Instantaneous",
       classes=[S,Wi],
       desc="A frigid beam of blue-white light streaks toward a creature. Ranged spell attack; on a hit deal 1d8 cold damage and reduce speed by 10 ft until start of your next turn."),
    sp("Resistance",       0,"Abjuration","1 action","Touch","V,S,M","Concentration, up to 1 minute",
       conc=True, classes=[C,D],
       desc="Touch a willing creature. Once before the spell ends, it can roll a d4 and add the result to one saving throw of its choice."),
    sp("Sacred Flame",     0,"Evocation","1 action","60 ft","V,S","Instantaneous",
       save="DEX", classes=[C],
       desc="Flame-like radiance descends on a creature you can see. DEX save (no benefit from cover) or take 1d8 radiant damage."),
    sp("Shillelagh",       0,"Transmutation","1 bonus action","Touch","V,S,M","1 minute",
       classes=[D],
       desc="Imbue a club or quarterstaff. For the duration, use your spellcasting modifier instead of STR for attacks and damage, and the weapon deals 1d8 damage."),
    sp("Shocking Grasp",   0,"Evocation","1 action","Touch","V,S","Instantaneous",
       classes=[S,Wi],
       desc="Lightning springs from your hand. Melee spell attack (advantage vs metal armor). On a hit: 1d8 lightning damage and the target cannot take reactions until its next turn."),
    sp("Spare the Dying",  0,"Necromancy","1 action","Touch","V,S","Instantaneous",
       classes=[C],
       desc="Touch a living creature at 0 HP. It becomes stable. Does not affect undead or constructs."),
    sp("Thaumaturgy",      0,"Transmutation","1 action","30 ft","V","Up to 1 minute",
       classes=[C],
       desc="Manifest minor wonders: booming voice, flame flicker, tremors, eerie sounds, door bang open/shut, eyes turn color. Up to three effects at once."),
    sp("Thorn Whip",       0,"Transmutation","1 action","30 ft","V,S,M","Instantaneous",
       classes=[D],
       desc="Create a vine-like whip. Melee spell attack; on a hit deal 1d6 piercing damage and pull the creature up to 10 ft toward you."),
    sp("True Strike",      0,"Divination","1 action","30 ft","S","Concentration, up to 1 round",
       conc=True, classes=[B,S,Wa,Wi],
       desc="You extend your senses to a creature within range. On your next turn, you have advantage on your first attack roll against that creature."),
    sp("Vicious Mockery",  0,"Enchantment","1 action","60 ft","V","Instantaneous",
       save="WIS", classes=[B],
       desc="Unleash a string of insults. WIS save or take 1d4 psychic damage and have disadvantage on its next attack roll."),
]

# ── LEVEL 1 ────────────────────────────────────────────────────────────────────
L1 = [
    sp("Alarm",                         1,"Abjuration","1 minute","30 ft","V,S,M","8 hours",
       ritual=True, classes=[Ra,Wi],
       desc="Set an alarm against unwanted intrusion in or around a door, window, or area no larger than 20-ft cube. Mental (silent) or audible alarm when triggered."),
    sp("Armor of Agathys",              1,"Abjuration","1 action","Self","V,S,M","1 hour",
       classes=[Wa],
       desc="Protective magical frost. Gain 5 temporary HP (more at higher levels). If a creature hits you while you have these THP, it takes 5 cold damage."),
    sp("Arms of Hadar",                 1,"Conjuration","1 action","Self (10-ft radius)","V,S","Instantaneous",
       save="STR", classes=[Wa],
       desc="Tendrils of dark energy erupt from you. Each creature within 10 ft must make a STR save: fail = 2d6 necrotic damage and can't take reactions; success = half damage."),
    sp("Bane",                          1,"Enchantment","1 action","30 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="CHA", classes=[B,C,P],
       desc="Up to three creatures within range must make CHA saves. Failure: subtract 1d4 from all attack rolls and saving throws for the duration."),
    sp("Burning Hands",                 1,"Evocation","1 action","Self (15-ft cone)","V,S","Instantaneous",
       save="DEX", classes=[S,Wi],
       desc="A thin sheet of flames shoots from your outstretched fingers in a 15-ft cone. DEX save: fail = 3d6 fire damage; success = half."),
    sp("Charm Person",                  1,"Enchantment","1 action","30 ft","V,S","1 hour",
       save="WIS", classes=[B,D,S,Wa,Wi],
       desc="Attempt to charm a humanoid. WIS save (advantage if you or your allies are in combat with it). On fail, the creature regards you as a friendly acquaintance for the duration."),
    sp("Chromatic Orb",                 1,"Evocation","1 action","90 ft","V,S,M","Instantaneous",
       classes=[S,Wi],
       desc="Hurl a 4-in diameter sphere of energy. Make a ranged spell attack; choose acid, cold, fire, lightning, poison, or thunder damage. On hit: 3d8 of chosen damage."),
    sp("Color Spray",                   1,"Illusion","1 action","Self (15-ft cone)","V,S,M","1 round",
       classes=[S,Wi],
       desc="A dazzling array of flashing, colored light springs from your hand. Roll 6d10; blinded for 1 round in HP order starting from lowest, up to total rolled."),
    sp("Command",                       1,"Enchantment","1 action","60 ft","V","1 round",
       save="WIS", classes=[C,P],
       desc="Speak a one-word command to a creature you can see. WIS save or follow the command on its next turn. Commands: Approach, Drop, Flee, Grovel, Halt."),
    sp("Comprehend Languages",          1,"Divination","1 action","Self","V,S,M","1 hour",
       ritual=True, classes=[B,S,Wa,Wi],
       desc="For the duration, you understand the literal meaning of any spoken language you hear and written language you see."),
    sp("Detect Magic",                  1,"Divination","1 action","Self","V,S","Concentration, up to 10 minutes",
       conc=True, ritual=True, classes=[B,C,D,P,Ra,S,Wi],
       desc="Sense the presence of magic within 30 ft. You can use your action to see a faint aura around magical creatures/objects and learn their school of magic."),
    sp("Disguise Self",                 1,"Illusion","1 action","Self","V,S","1 hour",
       classes=[B,S,Wi,Ro],
       desc="Make yourself look different including clothing, armor, weapons, and equipment. You can appear up to 1 ft shorter or taller. Does not change body feel; Investigation check vs spell save DC to see through."),
    sp("Dissonant Whispers",            1,"Enchantment","1 action","60 ft","V","Instantaneous",
       save="WIS", classes=[B],
       desc="Whisper a discordant melody to a creature you can see. WIS save: fail = 3d6 psychic damage and must use reaction to move away; success = half, no movement."),
    sp("Expeditious Retreat",           1,"Transmutation","1 bonus action","Self","V,S","Concentration, up to 10 minutes",
       conc=True, classes=[S,Wa,Wi],
       desc="This spell allows you to move at an incredible pace. When you cast and as a bonus action on subsequent turns, you can take the Dash action."),
    sp("Faerie Fire",                   1,"Evocation","1 action","60 ft","V","Concentration, up to 1 minute",
       conc=True, save="DEX", classes=[B,D],
       desc="Objects/creatures in a 20-ft cube are outlined in blue, green, or violet light. DEX save or shed dim light 10 ft and attack rolls against them have advantage. Invisible creatures are visible."),
    sp("False Life",                    1,"Necromancy","1 action","Self","V,S,M","1 hour",
       classes=[S,Wi],
       desc="Bolster yourself with necromantic energy. Gain 1d4+4 temporary hit points (more at higher levels)."),
    sp("Feather Fall",                  1,"Transmutation","1 reaction","60 ft","V,M","1 minute",
       classes=[B,S,Wi],
       desc="Reaction when you or a creature within 60 ft falls. Up to five falling creatures descend at 60 ft/round and take no damage from falling."),
    sp("Find Familiar",                 1,"Conjuration","1 hour","10 ft","V,S,M","Instantaneous",
       ritual=True, classes=[Wi],
       desc="Gain the service of a familiar: bat, cat, crab, frog, hawk, lizard, octopus, owl, rat, raven, sea horse, spider, or weasel. The familiar acts independently, obeys your commands, and can deliver touch spells."),
    sp("Fog Cloud",                     1,"Conjuration","1 action","120 ft","V,S","Concentration, up to 1 hour",
       conc=True, classes=[D,Ra,S,Wi],
       desc="Create a 20-ft radius sphere of fog centered on a point within range. The sphere spreads around corners; heavily obscured."),
    sp("Grease",                        1,"Conjuration","1 action","60 ft","V,S,M","1 minute",
       save="DEX", classes=[Wi],
       desc="Slick grease covers the ground in a 10-ft square. DEX save or fall prone. Difficult terrain for the duration."),
    sp("Hellish Rebuke",                1,"Evocation","1 reaction","60 ft","V,S","Instantaneous",
       save="DEX", classes=[Wa],
       desc="Reaction when damaged by a creature within 60 ft. The creature is momentarily surrounded by flames; DEX save or take 2d10 fire damage (success = half)."),
    sp("Hex",                           1,"Enchantment","1 bonus action","90 ft","V,S,M","Concentration, up to 1 hour",
       conc=True, classes=[Wa],
       desc="Curse a creature. It takes an extra 1d6 necrotic damage when you hit it with an attack. Choose an ability score; the target has disadvantage on checks using it. Bonus action to move curse if target drops to 0 HP."),
    sp("Ice Knife",                     1,"Conjuration","1 action","60 ft","S,M","Instantaneous",
       save="DEX", classes=[D,S,Wi],
       desc="Create a shard of ice and fling it at a creature. Ranged spell attack: 1d10 piercing on hit. Then explodes: DEX save or 2d6 cold damage to each creature within 5 ft."),
    sp("Identify",                      1,"Divination","1 minute","Touch","V,S,M","Instantaneous",
       ritual=True, classes=[B,Wi],
       desc="Choose one object you hold or one creature you touch. Learn its magical properties, how to use them, whether it requires attunement, and any active spells on it."),
    sp("Illusory Script",               1,"Illusion","1 minute","Touch","S,M","10 days",
       ritual=True, classes=[B,Wa,Wi],
       desc="Write on parchment or similar. To others it appears as unreadable scrawl or another language of your choice. Designated creatures read it normally."),
    sp("Jump",                          1,"Transmutation","1 action","Touch","V,S,M","1 minute",
       classes=[D,Ra,S,Wi],
       desc="Touch a creature. Its jump distance is tripled for the duration."),
    sp("Longstrider",                   1,"Transmutation","1 action","Touch","V,S,M","1 hour",
       classes=[B,D,Ra,Wi],
       desc="Touch a creature. Its speed increases by 10 ft for the duration."),
    sp("Mage Armor",                    1,"Abjuration","1 action","Touch","V,S,M","8 hours",
       classes=[S,Wi],
       desc="Touch a willing creature who isn't wearing armor. Its base AC becomes 13 + DEX modifier. The spell ends if the target dons armor."),
    sp("Magic Missile",                 1,"Evocation","1 action","120 ft","V,S","Instantaneous",
       classes=[S,Wi],
       desc="Create three glowing darts of magical force. Each dart hits automatically for 1d4+1 force damage. All darts can hit one target or several. One extra dart per slot level above 1st."),
    sp("Protection from Evil and Good", 1,"Abjuration","1 action","Touch","V,S,M","Concentration, up to 10 minutes",
       conc=True, classes=[C,D,P,Wa,Wi],
       desc="Touch a willing creature. Protected from aberrations, celestials, elementals, fey, fiends, and undead: attacks against it have disadvantage; immunity to charm/frighten/possession by those types."),
    sp("Ray of Sickness",               1,"Necromancy","1 action","60 ft","V,S","Instantaneous",
       save="CON", classes=[S,Wi],
       desc="Make a ranged spell attack. On hit: 2d8 poison damage; CON save or poisoned until end of your next turn."),
    sp("Shield",                        1,"Abjuration","1 reaction","Self","V,S","1 round",
       classes=[S,Wi],
       desc="Reaction when you are hit by an attack or targeted by Magic Missile. +5 bonus to AC (retroactively making the attack miss) and immune to Magic Missile until start of next turn."),
    sp("Silent Image",                  1,"Illusion","1 action","60 ft","V,S,M","Concentration, up to 10 minutes",
       conc=True, classes=[B,S,Wi],
       desc="Create the visual illusion of an object, creature, or phenomenon no larger than a 15-ft cube. Investigation check vs spell save DC to see through."),
    sp("Silvery Barbs",                 1,"Enchantment","1 reaction","60 ft","V","Instantaneous",
       classes=[B,S,Wi], source="Strixhaven",
       desc="Reaction when a creature within 60 ft succeeds on an attack roll, saving throw, or ability check: force a reroll and take the lower result. Then choose a creature; it has advantage on the next roll it makes within 1 minute."),
    sp("Sleep",                         1,"Enchantment","1 action","90 ft","V,S,M","1 minute",
       classes=[B,S,Wi],
       desc="Roll 5d8; that many HP worth of creatures fall unconscious. Starting with lowest HP creatures; skips unconscious, immune, and undead. 2d8 extra per slot above 1st."),
    sp("Speak with Animals",            1,"Divination","1 action","Self","V,S","10 minutes",
       ritual=True, classes=[B,D,Ra],
       desc="You gain the ability to comprehend and verbally communicate with beasts for the duration. Knowledge limited to intelligence/memory of the beast."),
    sp("Tasha's Hideous Laughter",      1,"Enchantment","1 action","30 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[B,Wi],
       desc="A creature of your choice perceives everything as hilarious. WIS save or fall prone, incapacitated, unable to stand. Repeat save at end of each turn and when it takes damage."),
    sp("Tenser's Floating Disk",        1,"Conjuration","1 action","30 ft","V,S,M","1 hour",
       ritual=True, classes=[Wi],
       desc="Create a circular, horizontal plane of force 3 ft in diameter. Can hold up to 500 lbs. Hovers 3 ft off the ground and follows within 20 ft of you."),
    sp("Thunderwave",                   1,"Evocation","1 action","Self (15-ft cube)","V,S","Instantaneous",
       save="CON", classes=[B,D,S,Wi],
       desc="A wave of thunderous force sweeps out. Each creature in a 15-ft cube: CON save or take 2d8 thunder damage and be pushed 10 ft away (half damage, no push on success). Audible 300 ft."),
    sp("Unseen Servant",                1,"Conjuration","1 action","60 ft","V,S,M","1 hour",
       ritual=True, classes=[B,Wa,Wi],
       desc="Create an invisible mindless force that performs simple tasks at your command. AC 10, 1 HP, STR 2. Cannot attack or carry more than 10 lbs."),
    sp("Witch Bolt",                    1,"Evocation","1 action","30 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, classes=[S,Wa,Wi],
       desc="Ranged spell attack; on hit: 1d12 lightning damage. Subsequent turns: use action to deal 1d12 lightning automatically (beam breaks if target moves out of range)."),
]

# ── LEVEL 2 ────────────────────────────────────────────────────────────────────
L2 = [
    sp("Alter Self",               2,"Transmutation","1 action","Self","V,S","Concentration, up to 1 hour",
       conc=True, classes=[S,Wi],
       desc="Assume a different form. Choose: Aquatic Adaptation (breathe water, swim speed), Change Appearance (full physical alteration), or Natural Weapons (claws/fangs for 1d6 magical damage)."),
    sp("Arcane Lock",              2,"Abjuration","1 action","Touch","V,S,M","Until dispelled",
       classes=[Wi],
       desc="Touch a closed door, window, gate, or chest. It becomes magically locked. DC to break/pick increases by 10. You and designated creatures can open it normally."),
    sp("Blindness/Deafness",       2,"Necromancy","1 action","30 ft","V","1 minute",
       save="CON", classes=[B,C,S,Wi],
       desc="Blind or deafen a foe. CON save or blinded/deafened for 1 minute. Target repeats save at end of each turn."),
    sp("Blur",                     2,"Illusion","1 action","Self","V","Concentration, up to 1 minute",
       conc=True, classes=[S,Wi],
       desc="Your body becomes blurred. Attack rolls against you have disadvantage unless the attacker has blindsight, truesight, or doesn't rely on sight."),
    sp("Calm Emotions",            2,"Enchantment","1 action","60 ft","V,S","Concentration, up to 1 minute",
       conc=True, save="CHA", classes=[B,C],
       desc="Suppress strong emotions in a 20-ft radius sphere. Each creature: CHA save or (a) suppress charm/fright effects OR (b) become indifferent about hostile creatures."),
    sp("Cloud of Daggers",         2,"Conjuration","1 action","60 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, classes=[B,S,Wa,Wi],
       desc="Fill a 5-ft cube with spinning daggers. Any creature that enters or starts its turn in the area takes 4d4 slashing damage."),
    sp("Continual Flame",          2,"Evocation","1 action","Touch","V,S,M","Until dispelled",
       classes=[C,Wi],
       desc="A flame that produces no heat and requires no oxygen springs from an object. Looks like a regular torch flame but is magical and can't be extinguished by mundane means."),
    sp("Crown of Madness",         2,"Enchantment","1 action","120 ft","V,S","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[B,S,Wa,Wi],
       desc="WIS save or charmed; an iron crown appears on its head. On each of its turns it must attack a creature other than itself. You must use your action to maintain control each round."),
    sp("Darkness",                 2,"Evocation","1 action","60 ft","V,M","Concentration, up to 10 minutes",
       conc=True, classes=[S,Wa,Wi],
       desc="Magical darkness spreads from a point in a 15-ft radius. Darkvision is blocked; non-magical light cannot illuminate the area."),
    sp("Darkvision",               2,"Transmutation","1 action","Touch","V,S,M","8 hours",
       classes=[D,Ra,S,Wi],
       desc="Touch a willing creature. It gains darkvision out to 60 ft for the duration."),
    sp("Detect Thoughts",          2,"Divination","1 action","Self","V,S,M","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[B,S,Wi],
       desc="Read surface thoughts of a creature you can see. WIS save resists deeper probing. Can also detect presence of thinking creatures (not beasts) within 30 ft."),
    sp("Enhance Ability",          2,"Transmutation","1 action","Touch","V,S,M","Concentration, up to 1 hour",
       conc=True, classes=[B,C,D,Ra,S],
       desc="Touch a creature; grant one of: Bear's Endurance (CON adv, 2d6 THP), Bull's Strength (STR adv, double carry), Cat's Grace (DEX adv, ignore 20 ft fall), Eagle's Splendor (CHA adv), Fox's Cunning (INT adv), Owl's Wisdom (WIS adv)."),
    sp("Enlarge/Reduce",           2,"Transmutation","1 action","30 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="CON", classes=[S,Wi],
       desc="Enlarge: double creature size, +1d4 weapon damage, advantage STR checks/saves. Reduce: halve size, -1d4 weapon damage, disadvantage STR checks/saves. CON save to resist."),
    sp("Enthrall",                 2,"Enchantment","1 action","60 ft","V,S","1 minute",
       save="WIS", classes=[B,Wa],
       desc="Weave a distracting string of words. Each creature you choose within 60 ft must make a WIS save or have disadvantage on Perception checks while you speak."),
    sp("Flaming Sphere",           2,"Conjuration","1 action","60 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="DEX", classes=[D,Wi],
       desc="A 5-ft diameter sphere of fire rolls around. Any creature that ends its turn within 5 ft: DEX save or 2d6 fire damage (half on success). Bonus action to move it up to 30 ft."),
    sp("Gentle Repose",            2,"Necromancy","1 action","Touch","V,S,M","10 days",
       ritual=True, classes=[C,Wi],
       desc="Touch a corpse or remains. Protected from decay and cannot become undead. Also extends time limit for resurrection spells by 10 days."),
    sp("Gust of Wind",             2,"Evocation","1 action","Self (60-ft line)","V,S,M","Concentration, up to 1 minute",
       conc=True, save="STR", classes=[D,S,Wi],
       desc="60-ft line, 10-ft wide. STR save or pushed 15 ft away. Difficult terrain moving toward you. Can extinguish flames and disperse fog."),
    sp("Hold Person",              2,"Enchantment","1 action","60 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[B,C,D,S,Wa,Wi],
       desc="Choose a humanoid within range. WIS save or paralyzed. Repeat save at end of each turn. One additional humanoid per slot level above 2nd."),
    sp("Invisibility",             2,"Illusion","1 action","Touch","V,S,M","Concentration, up to 1 hour",
       conc=True, classes=[B,S,Wa,Wi],
       desc="A creature you touch becomes invisible. Ends if target attacks or casts a spell. One additional target per slot level above 2nd."),
    sp("Knock",                    2,"Transmutation","1 action","60 ft","V","Instantaneous",
       classes=[S,Wi],
       desc="Loudly open a locked door, window, chest, or shackles. Audible 300 ft. Suppresses arcane lock for 10 minutes."),
    sp("Levitate",                 2,"Transmutation","1 action","60 ft","V,S,M","Concentration, up to 10 minutes",
       conc=True, save="CON", classes=[S,Wi],
       desc="One creature or loose object (500 lbs max) rises vertically up to 20 ft. Unwilling creature: CON save. Target can move only by pushing against a solid surface."),
    sp("Locate Object",            2,"Divination","1 action","Self","V,S,M","Concentration, up to 10 minutes",
       conc=True, classes=[B,C,D,P,Ra,Wi],
       desc="Sense the direction of a specific familiar object or the nearest object of a type within 1,000 ft. Blocked by lead."),
    sp("Magic Mouth",              2,"Illusion","1 minute","30 ft","V,S,M","Until dispelled",
       ritual=True, classes=[B,Wi],
       desc="Implant a spoken message of up to 25 words in an object. A mouth appears and speaks the message when your specified trigger occurs."),
    sp("Magic Weapon",             2,"Transmutation","1 bonus action","Touch","V,S","Concentration, up to 1 hour",
       conc=True, classes=[P,Wi],
       desc="Touch a nonmagical weapon. It becomes a magic weapon with +1 bonus to attack/damage rolls. +2 at slot 4, +3 at slot 6."),
    sp("Melf's Acid Arrow",        2,"Evocation","1 action","90 ft","V,S,M","Instantaneous",
       classes=[Wi],
       desc="Ranged spell attack. Hit: 4d4 acid damage immediately, 2d4 at end of target's next turn. Miss: 2d4 acid damage, no lingering."),
    sp("Mirror Image",             2,"Illusion","1 action","Self","V,S","1 minute",
       classes=[S,Wa,Wi],
       desc="Three illusory duplicates of yourself appear. When attacked, roll d20; 6+ (3 images), 8+ (2 images), or 11+ (1 image) — the attack hits a duplicate instead, which disappears."),
    sp("Misty Step",               2,"Conjuration","1 bonus action","Self","V","Instantaneous",
       classes=[S,Wa,Wi],
       desc="Briefly surrounded by silvery mist, you teleport up to 30 ft to an unoccupied space you can see."),
    sp("Nystul's Magic Aura",      2,"Illusion","1 action","Touch","V,S,M","24 hours",
       classes=[Wi],
       desc="Place an illusion on a creature or object. Change what detection magic reveals: false alignment, false creature type, or false magic aura. Lasts 30 days when concentration dropped."),
    sp("Phantasmal Force",         2,"Illusion","1 action","60 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="INT", classes=[B,S,Wi],
       desc="Craft an illusion in the mind of a creature you can see. INT save or believe a 10-ft cube phantasm is real; takes 1d6 psychic damage each turn."),
    sp("Ray of Enfeeblement",      2,"Necromancy","1 action","60 ft","V,S","Concentration, up to 1 minute",
       conc=True, save="CON", classes=[Wa,Wi],
       desc="Ranged spell attack; on hit the target is weakened. Weapon attacks deal only half damage. CON save at end of each turn to end the effect."),
    sp("Rope Trick",               2,"Transmutation","1 action","Touch","V,S,M","1 hour",
       classes=[Wi],
       desc="Touch a rope up to 60 ft long; it rises into the air. An invisible extradimensional space opens at the upper end that can hold up to 8 Medium creatures."),
    sp("Scorching Ray",            2,"Evocation","1 action","120 ft","V,S","Instantaneous",
       classes=[S,Wi],
       desc="Create three rays of fire; make a separate ranged spell attack for each. Hit: 2d6 fire damage per ray. One additional ray per slot level above 2nd."),
    sp("See Invisibility",         2,"Divination","1 action","Self","V,S,M","1 hour",
       classes=[B,S,Wi],
       desc="For the duration, you see invisible creatures/objects as visible and can see into the Ethereal Plane."),
    sp("Shatter",                  2,"Evocation","1 action","60 ft","V,S,M","Instantaneous",
       save="CON", classes=[B,S,Wa,Wi],
       desc="Sudden loud ringing noise hits a 10-ft radius sphere. CON save: 3d8 thunder damage (half success). Nonmagical objects take damage automatically."),
    sp("Silence",                  2,"Illusion","1 action","120 ft","V,S","Concentration, up to 10 minutes",
       conc=True, ritual=True, classes=[B,C,Ra],
       desc="No sound can be created within or pass through a 20-ft radius sphere. Creatures inside are deafened; spells with verbal components can't be cast inside."),
    sp("Spider Climb",             2,"Transmutation","1 action","Touch","V,S,M","Concentration, up to 1 hour",
       conc=True, classes=[S,Wa,Wi],
       desc="Touch a willing creature. Until the spell ends, it can climb difficult surfaces including ceilings, hands free."),
    sp("Suggestion",               2,"Enchantment","1 action","30 ft","V,M","Concentration, up to 8 hours",
       conc=True, save="WIS", classes=[B,S,Wa,Wi],
       desc="Suggest a course of activity (one or two sentences). WIS save or follow the suggestion to the best of its ability. Must be reasonable; self-harm ends spell."),
    sp("Web",                      2,"Conjuration","1 action","60 ft","V,S,M","Concentration, up to 1 hour",
       conc=True, save="DEX", classes=[S,Wi],
       desc="Conjure a 20-ft cube of thick webs. Difficult terrain. DEX save or restrained. Restrained creature uses action (STR check vs spell DC) to break free. Web is flammable."),
]

# ── LEVEL 3 ────────────────────────────────────────────────────────────────────
L3 = [
    sp("Animate Dead",             3,"Necromancy","1 minute","10 ft","V,S,M","Instantaneous",
       classes=[C,Wi],
       desc="Raise up to a Medium/Small corpse or bones as a skeleton or zombie under your control for 24 hours. Refresh with re-cast. Up to 2 extra per slot above 3rd."),
    sp("Bestow Curse",             3,"Necromancy","1 action","Touch","V,S","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[B,C,Wi],
       desc="Touch a creature; WIS save or cursed. Effects: disadvantage on an ability, attacks, WIS save each turn or waste action, or extra necrotic damage. Higher slots: longer duration."),
    sp("Blink",                    3,"Transmutation","1 action","Self","V,S","1 minute",
       classes=[S,Wi],
       desc="At the end of each turn, roll d20. On 11+, vanish to the Ethereal Plane until the start of your next turn. Observe but can't be targeted; reappear in same spot or nearest unoccupied."),
    sp("Clairvoyance",             3,"Divination","10 minutes","1 mile","V,S,M","Concentration, up to 10 minutes",
       conc=True, classes=[B,C,S,Wi],
       desc="Create an invisible sensor at a location within 1 mile. See or hear through the sensor using your own senses. Can switch sense as your action."),
    sp("Counterspell",             3,"Abjuration","1 reaction","60 ft","S","Instantaneous",
       classes=[S,Wa,Wi],
       desc="Reaction when a creature within 60 ft casts a spell. Automatically counter spells of 3rd level or lower; for higher level, make ability check (DC 10 + spell level)."),
    sp("Daylight",                 3,"Evocation","1 action","60 ft","V,S","1 hour",
       classes=[C,D,P,Ra,S],
       desc="60-ft radius sphere of bright light (dim for another 60 ft). Magical darkness can't extinguish it unless it's a higher-level spell."),
    sp("Dispel Magic",             3,"Abjuration","1 action","120 ft","V,S","Instantaneous",
       classes=[B,C,D,P,S,Wa,Wi],
       desc="Choose a creature, object, or magical effect. Spells of 3rd level or lower are automatically dispelled; higher-level effects require ability check (DC 10 + spell level)."),
    sp("Fear",                     3,"Illusion","1 action","Self (30-ft cone)","V,S,M","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[B,S,Wa,Wi],
       desc="Project a phantasmal image of worst fears in a 30-ft cone. WIS save or drop held items, become frightened, must Dash away. Repeat save at end of each turn."),
    sp("Feign Death",              3,"Necromancy","1 action","Touch","V,S,M","1 hour",
       ritual=True, classes=[B,C,D,Wi],
       desc="Touch a willing creature. It appears dead — blinded, incapacitated, resistance to all damage except psychic, immunity to poison/disease. Speed 0. Still perceives surroundings."),
    sp("Fireball",                 3,"Evocation","1 action","150 ft","V,S,M","Instantaneous",
       save="DEX", classes=[S,Wi],
       desc="Bright streak expands to 20-ft radius explosion. DEX save: 8d8 fire damage (half success). Sets fire to flammable objects. +1d8 per slot above 3rd."),
    sp("Flame Arrows",             3,"Transmutation","1 action","Touch","V,S","Concentration, up to 1 hour",
       conc=True, classes=[D,Ra,S,Wi],
       desc="Touch a quiver of up to 12 pieces of ammunition. Each piece ignites; when fired, 1d6 extra fire damage on a hit.",
       source="Xanathar's"),
    sp("Fly",                      3,"Transmutation","1 action","Touch","V,S,M","Concentration, up to 10 minutes",
       conc=True, classes=[S,Wa,Wi],
       desc="Touch a willing creature. It gains a flying speed of 60 ft for the duration. One additional target per slot level above 3rd."),
    sp("Gaseous Form",             3,"Transmutation","1 action","Touch","V,S,M","Concentration, up to 1 hour",
       conc=True, classes=[S,Wa,Wi],
       desc="Transform a willing creature into a misty cloud: fly 10 ft, hover; can't attack/cast; resistance to nonmagical damage; can move through any gap/crack; immune to prone."),
    sp("Glyph of Warding",         3,"Abjuration","1 hour","Touch","V,S,M","Until discharged",
       classes=[B,C,Wi],
       desc="Inscribe a glyph on a surface or object. Set a trigger condition. Effect: explosive runes (20-ft radius, DEX save, 5d8 damage) or a stored spell of 3rd level or lower."),
    sp("Haste",                    3,"Transmutation","1 action","30 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, classes=[S,Wi],
       desc="+2 AC, advantage on DEX saves, double speed, and one extra action per turn (attack, Dash, Disengage, Hide, or Use Object). When spell ends, target can't move or act for 1 turn."),
    sp("Hunger of Hadar",          3,"Conjuration","1 action","150 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="DEX", classes=[Wa],
       desc="Open a rift to a dark realm in a 20-ft radius sphere. Heavily obscured; no light. Start of turn inside: CON save or 2d6 cold. End of turn inside: DEX save or 2d6 acid."),
    sp("Hypnotic Pattern",         3,"Illusion","1 action","120 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[B,S,Wa,Wi],
       desc="Twisting colorful pattern in a 30-ft cube. WIS save or charmed and incapacitated. Repeat save if takes damage or a creature uses action to shake it awake."),
    sp("Leomund's Tiny Hut",       3,"Evocation","1 minute","Self (10-ft radius)","V,S,M","8 hours",
       ritual=True, classes=[B,Wi],
       desc="A 10-ft radius dome protects you and up to 9 creatures. Temperature inside comfortable, no precipitation. Creatures can't enter (unless allowed). Not movable."),
    sp("Lightning Bolt",           3,"Evocation","1 action","Self (100-ft line)","V,S,M","Instantaneous",
       save="DEX", classes=[S,Wi],
       desc="100-ft long, 5-ft wide bolt of lightning. DEX save: 8d6 lightning damage (half success). Can ignite flammable objects. +1d6 per slot above 3rd."),
    sp("Magic Circle",             3,"Abjuration","1 minute","10 ft","V,S,M","1 hour",
       classes=[C,P,Wa,Wi],
       desc="Create a 10-ft radius, 20-ft tall cylinder of magical energy. Choose one type: celestials, elementals, fey, fiends, or undead. Chosen type cannot enter, charm/frighten/possess inside."),
    sp("Major Image",              3,"Illusion","1 action","120 ft","V,S,M","Concentration, up to 10 minutes",
       conc=True, classes=[B,S,Wa,Wi],
       desc="Create a visual, auditory, olfactory, and thermal illusion no larger than a 20-ft cube. At 6th+ level, illusion persists without concentration."),
    sp("Nondetection",             3,"Abjuration","1 action","Touch","V,S,M","8 hours",
       classes=[B,Ra,Wi],
       desc="Hide a target from divination magic. Can't be targeted by divination or perceived through magical scrying sensors."),
    sp("Phantom Steed",            3,"Illusion","1 minute","30 ft","V,S","1 hour",
       ritual=True, classes=[Wi],
       desc="Create a Large quasi-real horse-like creature (speed 100 ft). Only you can ride it. Disappears if it takes damage or moves more than 1 mile from its creation point."),
    sp("Plant Growth",             3,"Transmutation","1 action or 8 hours","150 ft","V,S","Instantaneous",
       classes=[B,D,Ra],
       desc="1 action: overgrow plants in 100-ft radius (difficult terrain). 8 hours: enrich land, producing twice normal food for 1 year."),
    sp("Protection from Energy",   3,"Abjuration","1 action","Touch","V,S","Concentration, up to 1 hour",
       conc=True, classes=[C,D,Ra,S,Wi],
       desc="Touch a willing creature. It has resistance to one energy type you choose: acid, cold, fire, lightning, or thunder."),
    sp("Remove Curse",             3,"Abjuration","1 action","Touch","V,S","Instantaneous",
       classes=[C,P,Wa,Wi],
       desc="Touch a creature or object. All curses on it end. Breaks attunement to a cursed magic item."),
    sp("Sending",                  3,"Evocation","1 action","Unlimited","V,S,M","1 round",
       classes=[B,C,Wi],
       desc="Send a 25-word message to a creature you know. It can reply with 25 words. Works across planes."),
    sp("Sleet Storm",              3,"Conjuration","1 action","150 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="DEX", classes=[D,S,Wi],
       desc="Driving sleet in a 20-ft radius, 40-ft high cylinder. Heavily obscured, difficult terrain. DEX save or fall prone when moving. Concentration check DC 10 when inside."),
    sp("Slow",                     3,"Transmutation","1 action","120 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[S,Wi],
       desc="Up to 6 creatures in a 40-ft cube: WIS save or slowed (half speed, -2 AC and DEX saves, no reactions, one attack per action, no bonus action spell). Repeat save each turn."),
    sp("Speak with Dead",          3,"Necromancy","1 action","10 ft","V,S,M","10 minutes",
       classes=[B,C],
       desc="Ask a corpse up to 5 questions. Uses knowledge the creature had in life. Speaks truthfully but evasively. Works once per corpse per 10 days."),
    sp("Stinking Cloud",           3,"Conjuration","1 action","90 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="CON", classes=[B,S,Wi],
       desc="20-ft radius cloud of nauseating yellow-green gas. Heavily obscured. CON save at start of turn while inside or waste action retching."),
    sp("Thunder Step",             3,"Conjuration","1 action","90 ft","V","Instantaneous",
       save="CON", classes=[S,Wa,Wi], source="Xanathar's",
       desc="Teleport up to 90 ft to an unoccupied space you can see with a crack of thunder. Each creature within 10 ft of origin: CON save or 3d10 thunder damage (half success)."),
    sp("Tongues",                  3,"Divination","1 action","Touch","V,M","1 hour",
       classes=[B,C,S,Wa,Wi],
       desc="Touch a creature. It can understand any spoken language and be understood by any creature that speaks at least one language."),
    sp("Vampiric Touch",           3,"Necromancy","1 action","Self","V,S","Concentration, up to 1 minute",
       conc=True, classes=[Wa,Wi],
       desc="Melee spell attack each turn as an action: 3d6 necrotic damage; regain HP equal to half damage dealt."),
    sp("Water Breathing",          3,"Transmutation","1 action","30 ft","V,S,M","24 hours",
       ritual=True, classes=[D,Ra,S,Wi],
       desc="Up to 10 willing creatures you can see can breathe underwater for the duration."),
    sp("Water Walk",               3,"Transmutation","1 action","30 ft","V,S,M","1 hour",
       ritual=True, classes=[C,D,Ra,S],
       desc="Up to 10 willing creatures can move across any liquid surface as if it were solid ground. Each creature can end the effect for itself at will."),
]

# ── LEVEL 4 ────────────────────────────────────────────────────────────────────
L4 = [
    sp("Arcane Eye",               4,"Divination","1 action","30 ft","V,S,M","Concentration, up to 1 hour",
       conc=True, classes=[Wi],
       desc="Create an invisible sensor you can see through. 30 ft darkvision, 60 ft normal vision. Move 30 ft per action. Can squeeze through 1-inch openings."),
    sp("Aura of Life",             4,"Abjuration","1 action","Self (30-ft radius)","V","Concentration, up to 10 minutes",
       conc=True, classes=[P],
       desc="Life-preserving aura. Nonhostile creatures have resistance to necrotic damage; max HP can't be reduced; creatures at 0 HP that start turn in range regain 1 HP."),
    sp("Banishment",               4,"Abjuration","1 action","60 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="CHA", classes=[C,P,S,Wa,Wi],
       desc="CHA save or banished. Native plane: safe demi-plane until concentration ends. Non-native plane: banished permanently if concentration lasts 1 minute."),
    sp("Blight",                   4,"Necromancy","1 action","30 ft","V,S","Instantaneous",
       save="CON", classes=[D,S,Wa,Wi],
       desc="Drain moisture from a creature. CON save: 8d8 necrotic damage (half success). Plants and plant creatures have disadvantage and take max damage."),
    sp("Compulsion",               4,"Enchantment","1 action","30 ft","V,S","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[B],
       desc="Choose creatures within 30 ft. WIS save or compelled. Bonus action to designate a direction; the target uses its movement toward it on its next turn."),
    sp("Confusion",                4,"Enchantment","1 action","90 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[B,D,S,Wi],
       desc="10-ft radius sphere. WIS save or confused (roll d10 each turn: 1=frozen, 2-6=random move, 7-8=attacks nearest, 9-10=acts normally). Repeat save at end of each turn."),
    sp("Conjure Minor Elementals",  4,"Conjuration","1 minute","90 ft","V,S","Concentration, up to 1 hour",
       conc=True, classes=[D,Wi],
       desc="Summon elementals with total CR ≤ 2. Choose from one CR 2, two CR 1, four CR 1/2, or eight CR 1/4. Obey your commands."),
    sp("Control Water",            4,"Transmutation","1 action","300 ft","V,S,M","Concentration, up to 10 minutes",
       conc=True, save="STR", classes=[C,D,Wi],
       desc="Flood, Part Water (100×300 ft trench), Redirect Flow, or Whirlpool (50-ft diameter; STR save or 2d8 bludgeoning, restrained) within a 100-ft cube."),
    sp("Death Ward",               4,"Abjuration","1 action","Touch","V,S","8 hours",
       classes=[C,P],
       desc="Touch a creature. The first time it would drop to 0 HP, it instead drops to 1 HP and the spell ends. Also negates effects that would kill it outright."),
    sp("Dimension Door",           4,"Conjuration","1 action","500 ft","V","Instantaneous",
       classes=[B,S,Wa,Wi],
       desc="Teleport up to 500 ft to a location you can see, visualize, or describe. Bring along one willing Medium or smaller creature within 5 ft."),
    sp("Dominate Beast",           4,"Enchantment","1 action","60 ft","V,S","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[D,S],
       desc="WIS save or charmed beast obeys mental commands for duration. Repeat save when it takes damage."),
    sp("Evard's Black Tentacles",  4,"Conjuration","1 action","90 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="DEX", classes=[Wi],
       desc="Squirming tentacles fill a 20-ft square. Difficult terrain. DEX save or restrained; 3d6 bludgeoning damage. Restrained creature: 3d6 damage at start of each turn; STR/DEX check to escape."),
    sp("Fabricate",                4,"Transmutation","10 minutes","120 ft","V,S","Instantaneous",
       classes=[Wi],
       desc="Convert raw materials into finished items of the same material. Volume up to 10-ft cube (or 1 cubic foot of metal). Requires tool proficiency for fine work."),
    sp("Fire Shield",              4,"Evocation","1 action","Self","V,S,M","10 minutes",
       classes=[Wi],
       desc="Wispy flames shroud your body; bright light 10 ft, dim 10 ft more. Choose warm (cold resistance, 2d8 fire back when hit) or chill (fire resistance, 2d8 cold back when hit)."),
    sp("Greater Invisibility",     4,"Illusion","1 action","Touch","V,S","Concentration, up to 1 minute",
       conc=True, classes=[B,S,Wi],
       desc="You or a creature you touch becomes invisible for the duration. Does NOT end if target attacks or casts spells."),
    sp("Hallucinatory Terrain",    4,"Illusion","10 minutes","300 ft","V,S,M","24 hours",
       save="INT", classes=[B,D,Wa,Wi],
       desc="Make natural terrain in a 150-ft cube look, sound, and smell like another kind of natural terrain. INT (Investigation) vs spell save DC to see through."),
    sp("Ice Storm",                4,"Evocation","1 action","300 ft","V,S,M","Instantaneous",
       save="DEX", classes=[D,S,Wi],
       desc="Hail in a 20-ft radius, 40-ft high cylinder. DEX save: 2d8 bludgeoning + 4d6 cold (half success). Difficult terrain until end of your next turn."),
    sp("Leomund's Secret Chest",   4,"Conjuration","1 action","Touch","V,S,M","Instantaneous",
       classes=[Wi],
       desc="Hide a chest on the Ethereal Plane. Recall it for 1 minute to access contents. Chest is 3×2×2 ft; holds 12 cubic feet of nonliving material. Fades after 60 days if not recalled."),
    sp("Locate Creature",          4,"Divination","1 action","Self","V,S,M","Concentration, up to 1 hour",
       conc=True, classes=[B,C,D,P,Ra,Wi],
       desc="Sense the direction of a creature (familiar type or specific individual) within 1,000 ft. Blocked by running water (10+ ft wide) or lead."),
    sp("Mordenkainen's Private Sanctum",4,"Abjuration","10 minutes","120 ft","V,S,M","24 hours",
       classes=[Wi],
       desc="Secure a 5–100 ft cube area: sound can't pass out, vision through can be prevented, diviners can't scry in, teleportation in/out blocked."),
    sp("Mordenkainen's Faithful Hound",4,"Conjuration","1 action","30 ft","V,S,M","8 hours",
       classes=[Wi],
       desc="Conjure an invisible watchdog. Barks when creatures approach within 30 ft. Bites creatures within 5 ft on your turn: +9 to hit, 4d8 piercing. Must stay within 100 ft of you."),
    sp("Otiluke's Resilient Sphere",4,"Evocation","1 action","30 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="DEX", classes=[Wi],
       desc="10-ft diameter sphere of shimmering force encloses a creature. DEX save or enclosed. Sphere is immune to all damage; nothing passes through."),
    sp("Phantasmal Killer",        4,"Illusion","1 action","120 ft","V,S","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[Wi],
       desc="Tap into nightmares. WIS save or frightened; takes 4d10 psychic at start of each turn. Repeat save each turn; on success spell ends. +1d10 per slot above 4th."),
    sp("Polymorph",                4,"Transmutation","1 action","60 ft","V,S,M","Concentration, up to 1 hour",
       conc=True, save="WIS", classes=[B,D,S,Wi],
       desc="Transform a creature into a beast (CR ≤ target's level/CR). WIS save for unwilling targets. Returns to original form at 0 HP."),
    sp("Stone Shape",              4,"Transmutation","1 action","Touch","V,S,M","Instantaneous",
       classes=[C,D,Wi],
       desc="Touch a stone object Medium or smaller, or a section of stone no more than 5 ft in any dimension. Reshape it into any form you like."),
    sp("Stoneskin",                4,"Abjuration","1 action","Touch","V,S,M","Concentration, up to 1 hour",
       conc=True, classes=[D,Ra,S,Wi],
       desc="Touch a willing creature. Its skin becomes rock-hard. Resistance to nonmagical bludgeoning, piercing, and slashing damage."),
    sp("Wall of Fire",             4,"Evocation","1 action","120 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="DEX", classes=[D,S,Wi],
       desc="Wall of fire (60-ft long, 20-ft high, 1-ft thick; or 20-ft diameter ring). Choose inner or outer face. End turn on chosen side: DEX save or 5d8 fire damage."),
]

# ── LEVEL 5 ────────────────────────────────────────────────────────────────────
L5 = [
    sp("Animate Objects",          5,"Transmutation","1 action","120 ft","V,S","Concentration, up to 1 minute",
       conc=True, classes=[B,S,Wi],
       desc="Animate up to 10 nonmagical objects not worn/carried. Bonus action to command. Stats scale by size: Tiny=1 HP/1d4+4 dmg, Small=10 HP/1d8+2, Medium=40 HP/2d6, Large=80 HP/2d10, Huge=200 HP/2d12+4."),
    sp("Bigby's Hand",             5,"Evocation","1 action","120 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, classes=[Wi],
       desc="Create a Large hand of force. Clenched Fist (4d8 force, bonus action), Forceful Hand (push), Grasping Hand (grapple STR +8, 2d6/turn), Interposing Hand (cover, half speed)."),
    sp("Cloudkill",                5,"Conjuration","1 action","120 ft","V,S","Concentration, up to 10 minutes",
       conc=True, save="CON", classes=[S,Wi],
       desc="20-ft radius sphere of yellow-green fog. Heavily obscured. 5d8 poison damage at start of turn inside (CON save = half). Moves 10 ft away from you each round."),
    sp("Cone of Cold",             5,"Evocation","1 action","Self (60-ft cone)","V,S,M","Instantaneous",
       save="CON", classes=[S,Wi],
       desc="Blast of cold air in 60-ft cone. CON save: 8d8 cold damage (half success). Creatures killed by this become frozen statues until they thaw."),
    sp("Conjure Elemental",        5,"Conjuration","1 minute","90 ft","V,S,M","Concentration, up to 1 hour",
       conc=True, classes=[D,Wi],
       desc="Summon an elemental of CR 5 or lower. Obeys your commands. If concentration breaks, it becomes hostile."),
    sp("Contact other Plane",      5,"Divination","1 minute","Self","V","1 minute",
       ritual=True, classes=[Wa,Wi],
       desc="Mentally contact a demigod, spirit, or cosmic being. Ask up to 5 questions (yes/no/maybe/unknown/misleading). INT save DC 15 or gain insanity for 1d6×10 hours."),
    sp("Contagion",                5,"Necromancy","1 action","Touch","V,S","7 days",
       save="CON", classes=[C,D],
       desc="Melee spell attack; on hit the target is diseased. 3 failed CON saves over 3 turns: fully diseased (blinding sickness, filth fever, flesh rot, mindfire, seizure, or slimy doom)."),
    sp("Creation",                 5,"Illusion","1 minute","30 ft","V,S,M","Special",
       classes=[S,Wi],
       desc="Create a nonliving object from shadow-stuff up to a 5-ft cube. Duration by material: vegetable 1 day, stone/crystal 12 hours, metals 1 hour, adamantine 1 minute."),
    sp("Dominate Person",          5,"Enchantment","1 action","60 ft","V,S","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[B,S,Wi],
       desc="WIS save or charmed humanoid obeys mental commands for duration. Repeat save when taking damage. +1 hour duration per slot above 5th."),
    sp("Dream",                    5,"Illusion","1 minute","Special","V,S,M","8 hours",
       classes=[B,Wa,Wi],
       desc="Target a sleeping creature. Enter a trance to shape their dream environment. Can send a nightmare (WIS save or 3d6 psychic + no benefit from rest)."),
    sp("Far Step",                 5,"Conjuration","1 bonus action","Self","V","Concentration, up to 1 minute",
       conc=True, classes=[S,Wa,Wi], source="Xanathar's",
       desc="Teleport up to 60 ft to an unoccupied space you can see. On each turn for the duration, you can teleport again as a bonus action."),
    sp("Flame Strike",             5,"Evocation","1 action","60 ft","V,S,M","Instantaneous",
       save="DEX", classes=[C],
       desc="10-ft radius, 40-ft high column of divine fire. DEX save: 4d6 fire + 4d6 radiant (half success). +1d6 fire + 1d6 radiant per slot above 5th."),
    sp("Geas",                     5,"Enchantment","1 minute","60 ft","V","30 days",
       save="WIS", classes=[B,C,D,P,Wi],
       desc="WIS save or compelled to carry out a service or refrain from an action. Disobeying: 5d10 psychic each day. Higher slots: longer duration (permanent at 9th)."),
    sp("Hallow",                   5,"Evocation","24 hours","Touch","V,S,M","Until dispelled",
       classes=[C],
       desc="Infuse an area up to 60-ft radius with divine energy. Prevents planar travel. Choose an additional effect: courage, darkness, daylight, energy resistance, extradimensional interference, fear, silence, or tongues."),
    sp("Hold Monster",             5,"Enchantment","1 action","90 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[B,S,Wa,Wi],
       desc="WIS save or paralyzed (any creature type, not just humanoids). Repeat save at end of each turn."),
    sp("Insect Plague",            5,"Conjuration","1 action","300 ft","V,S,M","Concentration, up to 10 minutes",
       conc=True, save="CON", classes=[C,D,S],
       desc="20-ft radius sphere of stinging wasps. Lightly obscured. CON save at start of turn inside: 4d10 piercing (half success). +1d10 per slot above 5th."),
    sp("Legend Lore",              5,"Divination","10 minutes","Self","V,S,M","Instantaneous",
       classes=[B,C,Wi],
       desc="Name a person, place, or object. If legendary, you learn lore about it in cryptic but accurate rhymes or poems."),
    sp("Mislead",                  5,"Illusion","1 action","Self","S","Concentration, up to 1 hour",
       conc=True, classes=[B,Wi],
       desc="Become invisible and simultaneously create an illusory double in your space. Bonus action to move the double. You see and hear through the double with your action."),
    sp("Modify Memory",            5,"Enchantment","1 action","30 ft","V,S","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[B,Wi],
       desc="WIS save or incapacitated. Within 1 minute, alter memory of an event in the last 24 hours lasting no more than 10 minutes. Higher slots: older memories."),
    sp("Passwall",                 5,"Transmutation","1 action","30 ft","V,S,M","1 hour",
       classes=[Wi],
       desc="Create a passage through a wooden, plaster, or stone wall up to 20 ft thick. Passage is 5 ft wide, 8 ft tall, 20 ft deep. Creatures inside when it closes are expelled unharmed."),
    sp("Planar Binding",           5,"Abjuration","1 hour","60 ft","V,S,M","24 hours",
       save="CHA", classes=[B,C,D,Wi],
       desc="Bind a celestial, elemental, fey, or fiend within 60 ft. CHA save or forced to serve you. +1 day per slot above 5th (up to 1 year at 9th)."),
    sp("Raise Dead",               5,"Necromancy","1 hour","Touch","V,S,M","Instantaneous",
       classes=[B,C,P],
       desc="Return a dead creature to life (died within 10 days). Returns with 1 HP. Cannot restore missing body parts. -4 to all d20 rolls for 4 days (reduces by 1 each long rest)."),
    sp("Rary's Telepathic Bond",   5,"Divination","1 action","30 ft","V,S,M","1 hour",
       ritual=True, classes=[Wi],
       desc="Forge telepathic links among up to 8 willing creatures. Linked creatures communicate telepathically across any distance (same plane)."),
    sp("Reincarnate",              5,"Transmutation","1 hour","Touch","V,S,M","Instantaneous",
       classes=[D],
       desc="Touch a dead humanoid (died within 10 days). Soul inhabits a new young adult body of a randomly determined race. Retains all mental scores, class features, and memories."),
    sp("Scrying",                  5,"Divination","10 minutes","Self","V,S,M","Concentration, up to 10 minutes",
       conc=True, save="WIS", classes=[B,C,D,Wa,Wi],
       desc="WIS save (modified by familiarity) or you can see and hear the target anywhere on the same plane. An invisible sensor appears nearby."),
    sp("Seeming",                  5,"Illusion","1 action","30 ft","V,S","8 hours",
       save="CHA", classes=[B,S,Wi],
       desc="Change the appearance of any number of creatures within range. CHA save for unwilling targets. Each creature looks, sounds, and smells different within reason."),
    sp("Telekinesis",              5,"Transmutation","1 action","60 ft","V,S","Concentration, up to 10 minutes",
       conc=True, save="STR", classes=[S,Wi],
       desc="Move a creature or object up to 1,000 lbs. Object: 30 ft per turn. Creature: STR save or moved up to 30 ft; restrained while you maintain concentration."),
    sp("Teleportation Circle",     5,"Conjuration","1 minute","10 ft","V,M","1 round",
       classes=[B,S,Wi],
       desc="Create a shimmering portal connected to a permanent teleportation circle you know the sigil sequence for. Anyone stepping through is transported. Vanishes at end of your next turn."),
    sp("Transmute Rock",           5,"Transmutation","1 action","120 ft","V,S,M","Until dispelled",
       save="DEX", classes=[D,Wi], source="Xanathar's",
       desc="Rock to Mud: 40-ft cube of rock becomes thick mud (difficult terrain; ceiling collapse). Mud to Rock: reverses. DEX save or restrained for mud-to-rock."),
    sp("Wall of Force",            5,"Evocation","1 action","120 ft","V,S,M","Concentration, up to 10 minutes",
       conc=True, classes=[Wi],
       desc="Invisible wall of force up to ten 10-ft panels (flat or sphere). Immune to all damage and most spells. Nothing passes through; blocks teleportation."),
    sp("Wall of Stone",            5,"Evocation","1 action","120 ft","V,S,M","Concentration, up to 10 minutes",
       conc=True, save="DEX", classes=[D,S,Wi],
       desc="Create a nonmagical wall of solid stone: up to ten 10-ft×10-ft×6-in panels. DEX save or trapped if a panel closes on them. Permanent if concentration lasts full duration."),
]

# ── LEVEL 6 ────────────────────────────────────────────────────────────────────
L6 = [
    sp("Arcane Gate",              6,"Conjuration","1 action","500 ft","V,S","Concentration, up to 10 minutes",
       conc=True, classes=[S,Wa,Wi],
       desc="Create two linked portals (up to 10 ft diameter). Anyone entering one portal exits from the other."),
    sp("Chain Lightning",          6,"Evocation","1 action","150 ft","V,S,M","Instantaneous",
       save="DEX", classes=[S,Wi],
       desc="Primary target: DEX save or 10d8 lightning. Lightning leaps to three other targets within 30 ft; same save and damage. +1 additional target per slot above 6th."),
    sp("Circle of Death",          6,"Necromancy","1 action","150 ft","V,S,M","Instantaneous",
       save="CON", classes=[S,Wa,Wi],
       desc="60-ft radius sphere of negative energy. CON save: 8d6 necrotic damage (half success). +2d6 per slot above 6th."),
    sp("Conjure Fey",              6,"Conjuration","1 minute","90 ft","V,S","Concentration, up to 1 hour",
       conc=True, classes=[D,Wa],
       desc="Summon a fey creature of CR 6 or lower. Obeys commands. If concentration breaks, the fey may become hostile."),
    sp("Contingency",              6,"Evocation","10 minutes","Self","V,S,M","10 days",
       classes=[Wi],
       desc="Choose a spell of 5th level or lower that targets you. Set a condition; when that condition occurs, the contingency spell fires automatically."),
    sp("Create Undead",            6,"Necromancy","1 minute","10 ft","V,S,M","Instantaneous",
       classes=[C,Wa,Wi],
       desc="Raise up to three corpses as ghouls under your control (active at night only). Refresh control each day. Slot 7 = ghasts/wights; slot 8 = mummies; slot 9 = liches."),
    sp("Disintegrate",             6,"Transmutation","1 action","60 ft","V,S,M","Instantaneous",
       save="DEX", classes=[S,Wi],
       desc="DEX save or 10d6+40 force damage. If this reduces target to 0 HP, it and everything nonmagical on it turns to fine gray dust. +3d6 per slot above 6th."),
    sp("Drawmij's Instant Summons",6,"Conjuration","1 minute","Touch","V,S,M","Until dispelled",
       ritual=True, classes=[Wi],
       desc="Touch a Small or smaller object. You can use a bonus action to speak its name and teleport it to your hand from any distance (same plane)."),
    sp("Eyebite",                  6,"Necromancy","1 action","Self","V,S","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[B,S,Wa,Wi],
       desc="Your eyes become inky voids. Each turn, choose one creature within 60 ft: WIS save or asleep (d10+10 rounds), panicked, or sickened (disadvantage on attacks and ability checks)."),
    sp("Flesh to Stone",           6,"Transmutation","1 action","60 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="CON", classes=[Wi],
       desc="CON save each turn (3 saves to resist, 3 fails to petrify). While resisting: restrained, speed 0. 3 fails = petrified permanently until remove curse or greater restoration."),
    sp("Globe of Invulnerability", 6,"Abjuration","1 action","Self (10-ft radius)","V,S,M","Concentration, up to 1 minute",
       conc=True, classes=[S,Wi],
       desc="Shimmering sphere blocks spells of 5th level and lower from affecting creatures inside. Spells cast from inside can travel out. +1 level blocked per slot above 6th."),
    sp("Guards and Wards",         6,"Abjuration","10 minutes","Touch","V,S,M","24 hours",
       classes=[B,Wi],
       desc="Protect a building up to 2,500 sq ft per level. Effects: obscuring fog, magic mouths, dancing lights, webs, locked doors, confusion corridors."),
    sp("Magic Jar",                6,"Necromancy","1 minute","Self","V,S,M","Until dispelled",
       save="CHA", classes=[Wi],
       desc="Your soul enters a container within 100 ft. Attempt to possess any humanoid within 100 ft (CHA save). While possessing: use its body; it can't act; you retain INT/WIS/CHA."),
    sp("Mass Suggestion",          6,"Enchantment","1 action","60 ft","V,M","24 hours",
       save="WIS", classes=[B,S,Wa,Wi],
       desc="Like Suggestion but affects up to 12 creatures. Duration 24 hours at 6th. 10 days at 7th, 30 days at 8th, 1 year at 9th."),
    sp("Move Earth",               6,"Transmutation","1 action","120 ft","V,S,M","Concentration, up to 2 hours",
       conc=True, classes=[D,S,Wi],
       desc="Reshape dirt, sand, or clay in a 40-ft cube. Create/destroy trenches, raise/lower hills. Each alteration takes 10 minutes."),
    sp("Otiluke's Freezing Sphere",6,"Evocation","1 action","300 ft","V,S,M","Instantaneous",
       save="CON", classes=[Wi],
       desc="Globe of cold energy (100-ft radius burst). CON save: 10d6 cold (half success). Can delay effect or toss as grenade. Freezes water 6 inches deep."),
    sp("Otto's Irresistible Dance",6,"Enchantment","1 action","30 ft","V","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[B,Wi],
       desc="Target begins a comic dance. WIS save at end of each turn to break free. While dancing: speed 0, disadvantage on DEX saves and attack rolls, enemies have advantage against it."),
    sp("Programmed Illusion",      6,"Illusion","1 action","120 ft","V,S,M","Until dispelled",
       classes=[B,Wi],
       desc="Create an illusion that activates under a specific condition (up to 30-ft cube). Activates for 5 minutes when triggered, then resets."),
    sp("Sunbeam",                  6,"Evocation","1 action","Self (60-ft line)","V,S,M","Concentration, up to 1 minute",
       conc=True, save="CON", classes=[D,S,Wi],
       desc="5-ft wide beam of brilliant light. CON save: 6d8 radiant and blinded 1 turn (half on success). Undead and oozes have disadvantage. Sheds bright/dim light 30/30 ft."),
    sp("True Seeing",              6,"Divination","1 action","Touch","V,S,M","1 hour",
       classes=[B,C,S,Wa,Wi],
       desc="Touch a willing creature. It gains truesight (60 ft), notices secret doors, and can see into the Ethereal Plane."),
    sp("Wall of Ice",              6,"Evocation","1 action","120 ft","V,S,M","Concentration, up to 10 minutes",
       conc=True, save="DEX", classes=[Wi],
       desc="Create a wall of ice on a solid surface (up to ten 10×10×1-ft panels, or a sphere/dome). DEX save or 10d6 cold. Wall has AC 12, 30 HP per panel; destroyed section leaves frigid air."),
]

# ── LEVEL 7 ────────────────────────────────────────────────────────────────────
L7 = [
    sp("Delayed Blast Fireball",   7,"Evocation","1 action","150 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="DEX", classes=[S,Wi],
       desc="A bead of yellow light bursts after up to 1 minute or when you end the spell. 20-ft radius: DEX save, 12d6 fire (half success). +1d6 damage per round delayed."),
    sp("Etherealness",             7,"Transmutation","1 action","Self","V,S","Up to 8 hours",
       classes=[B,C,S,Wa,Wi],
       desc="Step into the Border Ethereal. Move through solid matter; see into Material Plane. Not affected by most material conditions. Slot 8+ affects up to 3 willing creatures."),
    sp("Finger of Death",          7,"Necromancy","1 action","60 ft","V,S","Instantaneous",
       save="CON", classes=[S,Wa,Wi],
       desc="CON save: 7d8+30 necrotic damage (half success). Humanoid killed by this rises as zombie permanently under your control."),
    sp("Fire Storm",               7,"Evocation","1 action","150 ft","V,S","Instantaneous",
       save="DEX", classes=[C,D,S],
       desc="Up to ten 10-ft cubes of fire arranged how you like (each adjacent/diagonal). DEX save: 7d10 fire damage (half success). Flammable objects ignite."),
    sp("Forcecage",                7,"Evocation","1 action","100 ft","V,S,M","1 hour",
       save="CHA", classes=[B,Wa,Wi],
       desc="Invisible cage of magical force in a 20-ft cube (with bars) or 10-ft box. Creatures inside cannot leave by any means. No concentration required."),
    sp("Mirage Arcane",            7,"Illusion","10 minutes","Sight","V,S","10 days",
       classes=[B,D,Wi],
       desc="Make terrain within 1 mile look, sound, smell, and feel like another terrain type. Creatures believe the illusion completely (take appropriate damage)."),
    sp("Mordenkainen's Magnificent Mansion",7,"Conjuration","1 minute","300 ft","V,S,M","24 hours",
       classes=[B,Wi],
       desc="Conjure an extradimensional dwelling with up to 50 rooms. Up to 100 willing creatures may enter. Interior is fully furnished and comfortable."),
    sp("Mordenkainen's Sword",     7,"Evocation","1 action","60 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, classes=[B,Wi],
       desc="Summon a sword-shaped plane of force. Make melee spell attack as bonus action each turn: 3d10 force damage on hit."),
    sp("Plane Shift",              7,"Conjuration","1 action","Touch","V,S,M","Instantaneous",
       save="CHA", classes=[C,D,S,Wa,Wi],
       desc="Touch yourself or a willing creature to teleport to another plane. For unwilling targets: CHA save or banished to a plane you choose."),
    sp("Prismatic Spray",          7,"Evocation","1 action","Self (60-ft cone)","V,S","Instantaneous",
       save="DEX", classes=[S,Wi],
       desc="8 colors (roll d8 per target): red=10d6 fire, orange=10d6 acid, yellow=10d6 lightning, green=poison (CON or die), blue=CON or petrified, indigo=INT or insanity, violet=WIS or plane shift, 8=two colors."),
    sp("Project Image",            7,"Illusion","1 action","500 miles","V,S,M","Concentration, up to 1 day",
       conc=True, classes=[B,Wi],
       desc="Create an illusory double of yourself. See/hear through it and cast spells as if you were there. Destroyed if disbelieved or dispelled."),
    sp("Reverse Gravity",          7,"Transmutation","1 action","100 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="DEX", classes=[D,S,Wi],
       desc="Reverse gravity in a 50-ft radius, 100-ft high cylinder. Unsecured objects and creatures fall upward. DEX save to grab onto something."),
    sp("Sequester",                7,"Transmutation","1 action","Touch","V,S,M","Until dispelled",
       save="CHA", classes=[Wi],
       desc="A willing creature or object becomes invisible and can't be targeted by divination. Creature enters suspended animation (doesn't age or need food/water/air)."),
    sp("Simulacrum",               7,"Illusion","12 hours","Touch","V,S,M","Until dispelled",
       classes=[Wi],
       desc="Create an illusory duplicate from ice and snow with half the original's HP. Cannot regain HP except via the spell (10 gp per HP for 8 hours). Only one simulacrum at a time."),
    sp("Symbol",                   7,"Abjuration","1 minute","Touch","V,S,M","Until discharged",
       save="WIS", classes=[B,C,Wi],
       desc="Inscribe a harmful glyph. Effects: death, discord, fear, hopelessness, insanity, pain, sleep, or stunning. WIS save for most effects. Triggers by set conditions."),
    sp("Teleport",                 7,"Conjuration","1 action","10 ft","V","Instantaneous",
       classes=[B,S,Wi],
       desc="Teleport up to 8 willing creatures or an object (10-ft cube) to a destination on the same plane. Arrival accuracy depends on familiarity."),
]

# ── LEVEL 8 ────────────────────────────────────────────────────────────────────
L8 = [
    sp("Antimagic Field",          8,"Abjuration","1 action","Self (10-ft radius)","V,S,M","Concentration, up to 1 hour",
       conc=True, classes=[C,Wi],
       desc="10-ft radius antimagic sphere centered on you. Spells and magical effects are suppressed inside. Magic items work normally but properties are suppressed."),
    sp("Antipathy/Sympathy",       8,"Enchantment","1 hour","60 ft","V,S,M","10 days",
       save="WIS", classes=[D,Wi],
       desc="Cause an object/area to attract or repel specific types of creatures. WIS save or compelled to approach (sympathy) or flee (antipathy); further saves on subsequent days."),
    sp("Clone",                    8,"Necromancy","1 hour","Touch","V,S,M","Instantaneous",
       classes=[Wi],
       desc="Grow an inert duplicate of a living creature. If the original dies, its soul transfers to the clone (full HP, no memories after clone creation)."),
    sp("Control Weather",          8,"Transmutation","10 minutes","Self (5-mile radius)","V,S,M","Concentration, up to 8 hours",
       conc=True, classes=[C,D,Wi],
       desc="Take control of the weather in a 5-mile radius. Change precipitation, wind, and temperature by one step every 10 minutes."),
    sp("Demiplane",                8,"Conjuration","1 action","60 ft","S","1 hour",
       classes=[Wa,Wi],
       desc="Create a shadowy door leading to an empty 30-ft cube demiplane. Others can use the door. Use same door repeatedly with the same spell."),
    sp("Dominate Monster",         8,"Enchantment","1 action","60 ft","V,S","Concentration, up to 1 hour",
       conc=True, save="WIS", classes=[B,S,Wa,Wi],
       desc="WIS save or charmed; any creature type. Obeys mental commands for up to 1 hour. Repeat save when taking damage."),
    sp("Earthquake",               8,"Evocation","1 action","500 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, save="DEX", classes=[C,D,S],
       desc="100-ft radius intense shaking. Difficult terrain; concentration check DC 15 for casters. DEX save or prone. Fissures (10% chance); structures take 50 damage/round."),
    sp("Feeblemind",               8,"Enchantment","1 action","150 ft","V,S,M","Instantaneous",
       save="INT", classes=[B,D,Wa,Wi],
       desc="INT save or INT/CHA drop to 1; can't cast spells, activate items, or understand language. Repeat save every 30 days; 3 successes = end."),
    sp("Glibness",                 8,"Transmutation","1 action","Self","V","1 hour",
       classes=[B,Wa],
       desc="Whatever you say sounds true. CHA checks automatically = 15. Magic can't determine you're lying."),
    sp("Incendiary Cloud",         8,"Conjuration","1 action","150 ft","V,S","Concentration, up to 1 minute",
       conc=True, save="DEX", classes=[S,Wi],
       desc="20-ft radius, 20-ft tall cylinder of roiling smoke and embers. Heavily obscured. DEX save at start of turn inside: 10d8 fire (half success). Moves away 10 ft each round."),
    sp("Maze",                     8,"Conjuration","1 action","60 ft","V,S","Concentration, up to 10 minutes",
       conc=True, classes=[Wi],
       desc="Banish a creature into a labyrinthine demiplane. It can use its action to escape (DC 20 INT check). Returns when it escapes or spell ends."),
    sp("Mind Blank",               8,"Abjuration","1 action","Touch","V,S","24 hours",
       classes=[B,Wi],
       desc="Touch a willing creature. Immune to psychic damage, mind reading, divination magic, the charmed condition, and effects that sense or alter emotions."),
    sp("Power Word Stun",          8,"Enchantment","1 action","60 ft","V","Special",
       save="CON", classes=[B,S,Wa,Wi],
       desc="If target has 150 HP or fewer, it is stunned. CON save at end of each turn to end the effect."),
    sp("Sunburst",                 8,"Evocation","1 action","150 ft","V,S,M","Instantaneous",
       save="CON", classes=[D,S,Wi],
       desc="60-ft radius sphere of sunlight. CON save: 12d6 radiant and blinded 1 minute (half, no blind on success). Undead and oozes have disadvantage. Dispels magical darkness up to 8th level."),
    sp("Telepathy",                8,"Evocation","1 action","Unlimited","V,S,M","24 hours",
       classes=[Wi],
       desc="Forge a telepathic link with a willing creature you know. Communicate thoughts, senses, and emotions across any distance (same plane)."),
]

# ── LEVEL 9 ────────────────────────────────────────────────────────────────────
L9 = [
    sp("Astral Projection",        9,"Necromancy","1 hour","10 ft","V,S,M","Special",
       classes=[C,D,Wa,Wi],
       desc="Project yourself and up to 8 willing creatures into the Astral Plane. Silver cord connects spirit to physical body. Return if concentration breaks or silver cord is severed."),
    sp("Foresight",                9,"Divination","1 minute","Touch","V,S,M","8 hours",
       classes=[B,D,Wa,Wi],
       desc="Touch a willing creature. It can't be surprised; advantage on attack rolls, ability checks, and saving throws; all attack rolls against it have disadvantage."),
    sp("Gate",                     9,"Conjuration","1 action","60 ft","V,S,M","Concentration, up to 1 minute",
       conc=True, classes=[C,S,Wi],
       desc="Open a circular portal to another plane (5–20 ft diameter). Two-way passage for 1 minute. Can call a specific extraplanar creature; CHA save or drawn through."),
    sp("Imprisonment",             9,"Abjuration","1 minute","30 ft","V,S,M","Until dispelled",
       save="WIS", classes=[Wa,Wi],
       desc="WIS save or trapped in one of: buried, chained, hedged prison, minimus containment (gem), or slumber. Freed only by specific means named at casting."),
    sp("Meteor Swarm",             9,"Evocation","1 action","1 mile","V,S","Instantaneous",
       save="DEX", classes=[S,Wi],
       desc="Four spheres rain down to four points within range. 40-ft radius burst each: DEX save or 20d6 fire + 20d6 bludgeoning (half success). Spheres ignite flammable objects."),
    sp("Power Word Kill",          9,"Enchantment","1 action","60 ft","V","Instantaneous",
       classes=[B,S,Wa,Wi],
       desc="Speak a word of death. If the target has 100 HP or fewer, it dies instantly. No saving throw."),
    sp("Prismatic Wall",           9,"Abjuration","1 action","60 ft","V,S","10 minutes",
       save="DEX", classes=[Wi],
       desc="90-ft wide, 30-ft tall opaque wall of shimmering energy. Seven layers (red through violet) each with different damage/effects and methods of disabling."),
    sp("Shapechange",              9,"Transmutation","1 action","Self","V,S,M","Concentration, up to 1 hour",
       conc=True, classes=[D,Wi],
       desc="Assume the form of any creature with CR equal to your level or lower. Use its stats; retain INT/WIS/CHA, class features, and language. Bonus action to change form."),
    sp("Time Stop",                9,"Transmutation","1 action","Self","V","Instantaneous",
       classes=[S,Wi],
       desc="Briefly stop the flow of time. You take 1d4+1 turns in a row. Spell ends if you move or place an effect that would affect another creature."),
    sp("True Polymorph",           9,"Transmutation","1 action","30 ft","V,S,M","Concentration, up to 1 hour",
       conc=True, save="WIS", classes=[B,S,Wa,Wi],
       desc="Transform a creature or object into anything. WIS save for unwilling targets. Permanent if concentration lasts full hour."),
    sp("Weird",                    9,"Illusion","1 action","120 ft","V,S","Concentration, up to 1 minute",
       conc=True, save="WIS", classes=[Wi],
       desc="Draw on deepest fears of creatures in a 30-ft sphere. WIS save or frightened; takes 4d10 psychic at start of each turn while frightened (repeat save each turn)."),
    sp("Wish",                     9,"Conjuration","1 action","Self","V","Instantaneous",
       classes=[S,Wi],
       desc="The mightiest spell. Duplicate any spell of 8th level or lower, OR alter reality itself (DM discretion). Stress: 33% chance of never casting Wish again, and STR for 1d10 days. Safe uses: restore 20 creatures to full HP, remove curses/afflictions up to 10, grant 10 years protection."),
]

ALL_SPELLS = CANTRIPS + L1 + L2 + L3 + L4 + L5 + L6 + L7 + L8 + L9


def main():
    init_db()
    seeded = 0
    for spell in ALL_SPELLS:
        upsert_spell_reference(spell)
        seeded += 1
    total = count_spells_reference()
    print(f"Seeded {seeded} spells ({total} total in DB).")

    import sqlite3, os
    db = os.path.join(os.path.dirname(__file__), "dnd_game.db")
    with sqlite3.connect(db) as con:
        rows = con.execute(
            "SELECT level, COUNT(*) FROM spells_reference GROUP BY level ORDER BY level"
        ).fetchall()
    for lvl, cnt in rows:
        label = "Cantrip" if lvl == 0 else f"Level {lvl}"
        print(f"  {label}: {cnt}")


if __name__ == "__main__":
    main()
